program javaeditor;

{$WEAKLINKRTTI ON}
{$RTTI EXPLICIT METHODS([]) PROPERTIES([]) FIELDS([])}

uses
  madExcept,
  madLinkDisAsm,
  madListHardware,
  madListProcesses,
  madListModules,
  WinApi.Windows,
  Forms,
  ActiveX,
  Vcl.Themes,
  Vcl.Styles,
  Vcl.Styles.Utils.Menus in 'Styles\Vcl.Styles.Utils.Menus.pas',
  Vcl.Styles.Utils.Misc in 'Styles\Vcl.Styles.Utils.Misc.pas',
  Vcl.Styles.Utils.SysControls in 'Styles\Vcl.Styles.Utils.SysControls.pas',
  Vcl.Styles.Utils.SysStyleHook in 'Styles\Vcl.Styles.Utils.SysStyleHook.pas',
  Vcl.Styles.Utils.Graphics in 'Styles\Vcl.Styles.Utils.Graphics.pas',
  uVclStylesFix in 'Styles\uVclStylesFix.pas',
  VCLStyleSynEdit in 'Styles\VCLStyleSynEdit.pas',
  UJava in 'UJava.pas' {FJava},
  UConfiguration in 'UConfiguration.pas' {FConfiguration},
  UDlgGotoLine in 'UDlgGotoLine.pas' {FGotoLineDialog},
  UObjectGenerator in 'UObjectGenerator.pas' {FObjectGenerator},
  UDlgParameter in 'UDlgParameter.pas' {FParameterDialog},
  UJavaCommands in 'UJavaCommands.pas',
  UMessages in 'UMessages.pas' {FMessages},
  UDlgHelp in 'UDlgHelp.pas' {FHelpDialog},
  UDlgFavoriten in 'UDlgFavoriten.pas' {FFavoritenDialog},
  UUMLModule in 'essmodel\System\UUMLModule.pas' {DMUMLModule: TDataModule},
  UListeners in 'essmodel\Model\UListeners.pas',
  UIntegrator in 'essmodel\Integrator\UIntegrator.pas',
  UModel in 'essmodel\Model\UModel.pas',
  UCodeIntegrator in 'essmodel\Integrator\Code\UCodeIntegrator.pas',
  UViewIntegrator in 'essmodel\Integrator\View\UViewIntegrator.pas',
  UModelEntity in 'essmodel\Model\UModelEntity.pas',
  UDiagramFrame in 'essmodel\Integrator\View\UDiagramFrame.pas' {AFrameDiagram: TFrame},
  UIterators in 'essmodel\Model\UIterators.pas',
  UDocumentation in 'essmodel\Model\UDocumentation.pas',
  USugiyamaLayout in 'essmodel\Components\USugiyamaLayout.pas',
  UDlgOpenFolder in 'UDlgOpenFolder.pas' {FOpenFolderDialog},
  UImages in 'UImages.pas' {DMImages: TDataModule},
  UDlgAssociation in 'UDlgAssociation.pas' {FAssociationDialog},
  UWatches in 'UWatches.pas' {FWatches},
  UFileStructure in 'UFileStructure.pas' {FFileStructure},
  UCodeCompletion in 'UCodeCompletion.pas',
  UScpHint in 'UScpHint.pas' {FScpScpHint},
  UDlgUpdate in 'UDlgUpdate.pas' {FUpdateDialog},
  UObjectInspector in 'UObjectInspector.pas' {FObjectInspector},
  UFrmEditor in 'UFrmEditor.pas' {FEditForm},
  UFrmBaseform in 'UFrmBaseform.pas' {FForm},
  UDlgJarCreate in 'UDlgJarCreate.pas' {FJarCreateDialog},
  UFrmExplorer in 'UFrmExplorer.pas' {FExplorer},
  USubversion in 'USubversion.pas' {FSubversion},
  UDiff in 'TextDiff\UDiff.pas',
  UHashUnit in 'TextDiff\UHashUnit.pas',
  USynEditExDiff in 'TextDiff\USynEditExDiff.pas',
  UFrmTextDiff in 'TextDiff\UFrmTextDiff.pas' {FTextDiff},
  UDlgAbout in 'UDlgAbout.pas',
  UDlgClassEditor in 'UDlgClassEditor.pas' {FClassEditor},
  UDlgDownload in 'UDlgDownload.pas',
  JNI in 'Jni\JNI.pas',
  UEssConnectPanel in 'essmodel\Components\UEssConnectPanel.pas',
  UDlgConfigureTools in 'UDlgConfigureTools.pas',
  UGUIForm in 'UGUIForm.pas' {FGUIForm},
  ULink in 'ULink.pas',
  ELDlgBorder in 'Formdesigner\ELDlgBorder.pas' {FBorder},
  ELDlgImage in 'formdesigner\ELDlgImage.pas' {FIconEditor},
  ELDlgStringsEdit in 'Formdesigner\ELDlgStringsEdit.pas' {ELStringsEditorDlg},
  ELPropInsp in 'formdesigner\ELPropInsp.pas',
  ELSConsts in 'formdesigner\ELSConsts.pas',
  ELControls in 'formdesigner\ELControls.pas',
  ELUtils in 'formdesigner\ELUtils.pas',
  ELDsgnr in 'formdesigner\ELDsgnr.pas',
  ELHintWindow in 'formdesigner\ELHintWindow.pas',
  UBorderColorBox in 'Formdesigner\UBorderColorBox.pas',
  UComJava1 in 'Jni\UComJava1.pas',
  UJniWrapper1 in 'Jni\UJniWrapper1.pas',
  UDelphiIntegrator in 'essmodel\Integrator\Code\UDelphiIntegrator.pas',
  URtfdComponents in 'essmodel\Integrator\View\URtfdComponents.pas',
  URtfdDiagram in 'essmodel\Integrator\View\URtfdDiagram.pas',
  URtfdDiagramFrame in 'essmodel\Integrator\View\URtfdDiagramFrame.pas' {AFrameRtfdDiagram: TFrame},
  UCodeParser in 'essmodel\Integrator\Code\UCodeParser.pas',
  UDelphiParser in 'essmodel\Integrator\Code\UDelphiParser.pas',
  UJavaClass in 'essmodel\Integrator\Code\UJavaClass.pas',
  UJavaClassImport in 'essmodel\Integrator\Code\UJavaClassImport.pas',
  UJavaParser in 'essmodel\Integrator\Code\UJavaParser.pas',
  UCodeProvider in 'essmodel\Integrator\Code\UCodeProvider.pas',
  UFileProvider in 'essmodel\Integrator\Code\UFileProvider.pas',
  UJavaScanner in 'essmodel\Integrator\Code\UJavaScanner.pas',
  UFrmUMLdiagram in 'EssModel\System\UFrmUMLdiagram.pas' {FUMLForm},
  UDlgClasspath in 'UDlgClasspath.pas',
  UDlgMindstormsEV3 in 'UDlgMindstormsEV3.pas' {FMindstormsEV3Dialog},
  UDlgMindstorms in 'UDlgMindstorms.pas' {FMindstormsDialog},
  UTooltip in 'UTooltip.pas' {FTooltip},
  UDebugger in 'UDebugger.pas',
  UFXLabel in 'components\JavaFX\UFXLabel.pas',
  UJEComponents in 'components\UJEComponents.pas',
  UFXTextInput in 'components\JavaFX\UFXTextInput.pas',
  UFXButtonBase in 'components\JavaFX\UFXButtonBase.pas',
  UFXListView in 'components\JavaFX\UFXListView.pas',
  UFXComboBox in 'components\JavaFX\UFXComboBox.pas',
  UFXSpinner in 'components\JavaFX\UFXSpinner.pas',
  UFXScrollBar in 'components\JavaFX\UFXScrollBar.pas',
  UFXScrollPane in 'components\JavaFX\UFXScrollPane.pas',
  UFXGUIForm in 'components\JavaFX\UFXGUIForm.pas',
  UFXMenu in 'components\JavaFX\UFXMenu.pas',
  UFXSlider in 'components\JavaFX\UFXSlider.pas',
  UFXProgressBar in 'components\JavaFX\UFXProgressBar.pas',
  UFXToolBar in 'components\JavaFX\UFXToolBar.pas',
  UFXSeparator in 'components\JavaFX\UFXSeparator.pas',
  UFXLabeled in 'components\JavaFX\UFXLabeled.pas',
  UFXChoiceBox in 'components\JavaFX\UFXChoiceBox.pas',
  UFXHTMLEditor in 'components\JavaFX\UFXHTMLEditor.pas',
  UFXPagination in 'components\JavaFX\UFXPagination.pas',
  UFXFileChooser in 'components\JavaFX\UFXFileChooser.pas',
  UFXImageView in 'components\JavaFX\UFXImageView.pas',
  UFXWebView in 'components\JavaFX\UFXWebView.pas',
  UFXTableView in 'components\JavaFX\UFXTableView.pas',
  UFXMediaView in 'components\JavaFX\UFXMediaView.pas',
  UFXShape in 'components\JavaFX\UFXShape.pas',
  UFXSVGPath in 'components\JavaFX\UFXSVGPath.pas',
  UFXCircle in 'components\JavaFX\UFXCircle.pas',
  UFXBezier in 'components\JavaFX\UFXBezier.pas',
  UFXLine in 'components\JavaFX\UFXLine.pas',
  UFXText in 'components\JavaFX\UFXText.pas',
  UFXCanvas in 'components\JavaFX\UFXCanvas.pas',
  UFXTurtle in 'components\JavaFX\UFXTurtle.pas',
  UFXPolygon in 'components\JavaFX\UFXPolygon.pas',
  UFXRectangle in 'components\JavaFX\UFXRectangle.pas',
  SsBase in 'Util\ShellShock\SsBase.pas',
  SsConst in 'Util\ShellShock\SsConst.pas',
  SsDict in 'Util\ShellShock\SsDict.pas',
  SsDQue in 'Util\ShellShock\SsDQue.pas',
  SsList in 'Util\ShellShock\SsList.pas',
  SsRegEx in 'Util\ShellShock\SsRegEx.pas',
  SsShlDlg in 'Util\ShellShock\SsShlDlg.pas',
  SsStrms in 'Util\ShellShock\SsStrms.pas',
  StFileOp in 'Util\ShellShock\StFileOp.pas',
  StShlCtl in 'Util\ShellShock\StShlCtl.pas',
  StShlDD in 'Util\ShellShock\StShlDD.pas',
  JvGnugettext in 'Util\JvGnugettext.pas',
  JvTabBar in 'Util\JvTabBar.pas',
  UDlgMessage in 'Util\UDlgMessage.pas' {DlgMessage},
  UHTMLHelp in 'Util\UHTMLHelp.pas',
  UHTMLParser in 'Util\UHTMLParser.pas',
  UQueue in 'Util\UQueue.pas',
  USaveDialog in 'Util\USaveDialog.pas',
  UStringRessources in 'Util\UStringRessources.pas',
  UStyledMemo in 'Util\UStyledMemo.pas',
  UStyles in 'Util\UStyles.pas',
  UTabObject in 'Util\UTabObject.pas',
  UTree in 'Util\UTree.pas',
  UUtils in 'Util\UUtils.pas',
  UWindow in 'Util\UWindow.pas' {FWindow},
  UGit in 'UGit.pas' {FGit},
  UPanelTransparent in 'essmodel\Integrator\View\UPanelTransparent.pas',
  UJUnitTest in 'UJUnitTest.pas' {FJUnitTests},
  SynCompletionProposal in 'SynEdit\SynCompletionProposal.pas',
  SynEdit in 'SynEdit\SynEdit.pas',
  SynEditExport in 'SynEdit\SynEditExport.pas',
  SynEditHighlighter in 'SynEdit\SynEditHighlighter.pas',
  SynEditKbdHandler in 'SynEdit\SynEditKbdHandler.pas',
  SynEditKeyCmds in 'SynEdit\SynEditKeyCmds.pas',
  SynEditKeyConst in 'SynEdit\SynEditKeyConst.pas',
  SynEditMiscClasses in 'SynEdit\SynEditMiscClasses.pas',
  SynEditMiscProcs in 'SynEdit\SynEditMiscProcs.pas',
  SynEditPrint in 'SynEdit\SynEditPrint.pas',
  SynEditPrinterInfo in 'SynEdit\SynEditPrinterInfo.pas',
  SynEditPrintMargins in 'SynEdit\SynEditPrintMargins.pas',
  SynEditPrintTypes in 'SynEdit\SynEditPrintTypes.pas',
  SynEditRegexSearch in 'SynEdit\SynEditRegexSearch.pas',
  SynEditSearch in 'SynEdit\SynEditSearch.pas',
  SynEditStrConst in 'SynEdit\SynEditStrConst.pas',
  SynEditTextBuffer in 'SynEdit\SynEditTextBuffer.pas',
  SynEditTypes in 'SynEdit\SynEditTypes.pas',
  SynEditWildcardSearch in 'SynEdit\SynEditWildcardSearch.pas',
  SynEditWordWrap in 'SynEdit\SynEditWordWrap.pas',
  SynEditCodeFolding in 'SynEdit\SynEditCodeFolding.pas',
  SynEditPrintHeaderFooter in 'SynEdit\SynEditPrintHeaderFooter.pas',
  USynEditEx in 'SynEdit\USynEditEx.pas',
  SynExportHTML in 'SynEdit\SynExportHTML.pas',
  SynExportRTF in 'SynEdit\SynExportRTF.pas',
  SynHighlighterCss in 'SynEdit\SynHighlighterCss.pas',
  SynHighlighterGeneral in 'SynEdit\SynHighlighterGeneral.pas',
  SynHighlighterHashEntries in 'SynEdit\SynHighlighterHashEntries.pas',
  SynHighlighterHtml in 'SynEdit\SynHighlighterHtml.pas',
  SynHighlighterJava in 'SynEdit\SynHighlighterJava.pas',
  SynHighlighterMulti in 'SynEdit\SynHighlighterMulti.pas',
  SynHighlighterPas in 'SynEdit\SynHighlighterPas.pas',
  SynHighlighterPHP in 'SynEdit\SynHighlighterPHP.pas',
  SynTextDrawer in 'SynEdit\SynTextDrawer.pas',
  SynUnicode in 'SynEdit\SynUnicode.pas',
  SynUsp10 in 'SynEdit\SynUsp10.pas',
  uDockForm in 'Dockable\uDockForm.pas' {DockableForm},
  DockingUtils in 'Dockable\DockingUtils.pas',
  uTabHost in 'Dockable\uTabHost.pas' {TabDockHost},
  uConjoinHost in 'Dockable\uConjoinHost.pas' {ConjoinDockHost},
  UDlgConnect in 'SequenceDiagram\UDlgConnect.pas' {FConnectDialog},
  ULifeLine in 'SequenceDiagram\ULifeLine.pas',
  UFrmSequencediagram in 'SequenceDiagram\UFrmSequencediagram.pas' {FSequenceForm},
  USequencePanel in 'SequenceDiagram\USequencePanel.pas',
  UGenerateStructogram in 'Structogram\UGenerateStructogram.pas',
  UFrmStructogram in 'Structogram\UFrmStructogram.pas' {FStructogram},
  UTypes in 'Structogram\UTypes.pas',
  UParseThread in 'UParseThread.pas',
  UDlgMethodCall in 'UDlgMethodCall.pas' {FMethodCallDialog},
  UDlgStringsEditor in 'UDlgStringsEditor.pas' {FStringEditorDialog},
  UDlgUnicode in 'UDlgUnicode.pas' {FUnicodeDialog},
  UClassInsert in 'EssModel\System\UClassInsert.pas' {FClassInsert},
  SynEditHighlighterOptions in 'SynEdit\SynEditHighlighterOptions.pas',
  SynEditDataObject in 'SynEdit\SynEditDataObject.pas',
  SynEditDragDrop in 'SynEdit\SynEditDragDrop.pas',
  UFXComponents in 'Components\UFXComponents.pas',
  UAButton in 'Components\AWT\UAButton.pas',
  UACheckboxRadio in 'Components\AWT\UACheckboxRadio.pas',
  UAComboBox in 'Components\AWT\UAComboBox.pas',
  UALabel in 'Components\AWT\UALabel.pas',
  UAList in 'Components\AWT\UAList.pas',
  UAMenu in 'Components\AWT\UAMenu.pas',
  UAPanel in 'Components\AWT\UAPanel.pas',
  UAScrollBar in 'Components\AWT\UAScrollBar.pas',
  UAScrollPane in 'Components\AWT\UAScrollPane.pas',
  UATextArea in 'Components\AWT\UATextArea.pas',
  UATextField in 'Components\AWT\UATextField.pas',
  UJButton in 'Components\Swing\UJButton.pas',
  UJCheckboxRadio in 'Components\Swing\UJCheckboxRadio.pas',
  UJChooser in 'Components\Swing\UJChooser.pas',
  UJComboBox in 'Components\Swing\UJComboBox.pas',
  UJLabel in 'Components\Swing\UJLabel.pas',
  UJLayeredDesktopPane in 'Components\Swing\UJLayeredDesktopPane.pas',
  UJList in 'Components\Swing\UJList.pas',
  UJMenu in 'Components\Swing\UJMenu.pas',
  UJPanel in 'Components\Swing\UJPanel.pas',
  UJProgressBar in 'Components\Swing\UJProgressBar.pas',
  UJScrollBar in 'Components\Swing\UJScrollBar.pas',
  UJScrollPane in 'Components\Swing\UJScrollPane.pas',
  UJSeparator in 'Components\Swing\UJSeparator.pas',
  UJSlider in 'Components\Swing\UJSlider.pas',
  UJSpinner in 'Components\Swing\UJSpinner.pas',
  UJSplitPane in 'Components\Swing\UJSplitPane.pas',
  UJTabbedPane in 'Components\Swing\UJTabbedPane.pas',
  UJTable in 'Components\Swing\UJTable.pas',
  UJTextArea in 'Components\Swing\UJTextArea.pas',
  UJTextField in 'Components\Swing\UJTextField.pas',
  UJToolBar in 'Components\Swing\UJToolBar.pas',
  UJTree in 'Components\Swing\UJTree.pas',
  UAComponents in 'Components\UAComponents.pas',
  UJComponents in 'Components\UJComponents.pas',
  UJUtilities in 'Components\Swing\UJUtilities.pas',
  UJGuiForm in 'Components\Swing\UJGuiForm.pas',
  UTemplates in 'UTemplates.pas',
  UFrmBrowser in 'UFrmBrowser.pas' {FBrowser},
  UGUIDesigner in 'UGUIDesigner.pas' {FGUIDesigner},
  UNTProcess in 'UNTProcess.pas',
  UFXPane in 'Components\JavaFX\UFXPane.pas',
  UFXTreeView in 'Components\JavaFX\UFXTreeView.pas',
  UExecution in 'Interactive\UExecution.pas',
  UExecutionParser in 'Interactive\UExecutionParser.pas',
  Vcl.Menus in 'System\Vcl.Menus.pas',
  Vcl.Consts in 'System\Vcl.Consts.pas',
  UDlgEvaluate in 'UDlgEvaluate.pas' {FEvaluate},
  UGrepResults in 'FindInFiles\UGrepResults.pas',
  URegExSearch in 'FindInFiles\URegExSearch.pas',
  USearchOptions in 'FindInFiles\USearchOptions.pas',
  UDlgConfirmReplace in 'FindInFiles\UDlgConfirmReplace.pas' {FConfirmReplace},
  UDlgGrepSearch in 'FindInFiles\UDlgGrepSearch.pas' {FGrepSearch},
  UDlgReplace in 'FindInFiles\UDlgReplace.pas' {FReplace},
  UDlgSearch in 'FindInFiles\UDlgSearch.pas' {FSearch},
  UDlgSearchAbort in 'FindInFiles\UDlgSearchAbort.pas' {FSearchAbort},
  UZOrderControl in 'Util\UZOrderControl.pas',
  UConnection in 'EssModel\Components\UConnection.pas';

{$R *.RES}

// These flags remove errors of the formdesigner when using 64 bit and Delphi 11.3
{$SetPEFlags IMAGE_FILE_RELOCS_STRIPPED
  or IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP
  or IMAGE_FILE_NET_RUN_FROM_SWAP}

begin
  CoInitialize(nil);// due to TFBrowser
  {$WARNINGS OFF}
  ReportMemoryLeaksOnShutdown := DebugHook <> 0;
  {$WARNINGS ON}
  Application.ShowHint:= true;
  TStyleManager.SystemHooks := TStyleManager.SystemHooks - [shMenus, shDialogs];
  TFConfiguration.setGUIStyle;
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  SetDefaultUIFont(Application.DefaultFont);
  Application.Title:= 'Java-Editor';
  Application.CreateForm(TDMImages, DMImages);
  Application.CreateForm(TFJava, FJava);
  Application.Run;
end.
